language: perl6

os:
  - linux

perl6:
  - latest

sudo: true

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libuuid1; fi

install:
  - rakudobrew build zef
  - zef install .
